import Link from "next/link";
import PageHeading from "../_components/utils/page-heading";
import TitledCard from "@/components/ui/titled-card";

export default function About() {
  return (
    <>
      <PageHeading
        title="About"
        subtitle="What's all this??? Players, teams, sponsors, events, locations, hazards, games. What the hell are you even talking about? Can you give me a short explanation of what this is all about?"
      />
      <TitledCard
        title="What is this?"
        className="flex h-fit flex-col items-start gap-2 text-sm text-muted-foreground"
      >
        <p>
          <i>Polemos Royale</i> is a text based battle simulator, more
          specifically is a remake of my previous iteration of a text based
          battle simulator called just{" "}
          <Link
            href="polemos.aornum.zys"
            className="text-primary hover:underline"
          >
            Polemos
          </Link>{" "}
          This iteration is a complete rewrite of the game, with new features, a
          battle royalesque twist where there is a shrinking map.
        </p>
        <p>
          Inspiration from this game comes from{" "}
          <Link
            href={"https://brantsteele.net/hungergames/disclaimer.php"}
            className="text-primary hover:underline"
          >
            BrantSteele's Hunger Games Simulator
          </Link>{" "}
          which allows you to simulate a game of Hunger Games with characters of
          your choice. With my friends we thought this idea was cool so we
          decided to expand on it, allowing you to have more players and new
          mechanics such as a map, sponsors, locations, etc.
        </p>
      </TitledCard>
      <TitledCard
        title="What are all these things?"
        className="flex h-fit flex-col items-start gap-2 text-sm text-muted-foreground"
      >
        <p>
          Let's start with the most important thing, the players. Players are
          the characters that will be fighting in your game. They can be
          anything. We have created over 150 players each being part of a team.
          Teams are nothing more that a group of players, they aren't bound to
          play together, but rather are a way to organize your players into
          categories.
        </p>
        <p>
          The next thing we have is the sponsors. Sponsors the people behind the
          teams, in this case they are me and my friends. We each select an
          equal number of teams to sponsor and thus when these win or lose, we
          are the ones who get the win.
        </p>
        <p>
          The next thing we have is the events. Events are the things that
          happen in your game, they can be anything. Events include 2 sides,
          attackers and defenders, each side deals damage to the other. The
          event's are generic and the names of the people involved are replaced
          with the players names during the game.
        </p>
        <p>
          Finally, the last thing we have is the locations and hazards. These
          elements are what dictate what events can happen to each players. At
          any given point during a game players are in a given location, these
          locations can at the same time be hazardous. The game will then
          randomly decide what event will happen based on the pool of events
          generated by that location and the hazards in it.
        </p>
      </TitledCard>
    </>
  );
}
